version: 2
jobs:
  test_calc:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: node testCalc.js
  test_marks_grader:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: python testMarksGrader.py
workflows:
  version: 2
  app:
    jobs:
      - test_calc
      - test_marks_grader